from enum import Enum
from typing import List, Optional, Union, Dict, Any
from pydantic import BaseModel, Field

class QuestionType(str, Enum):
    """Enumeration of supported Google Form question types."""
    SHORT_ANSWER = "short_answer"
    PARAGRAPH = "paragraph"
    MULTIPLE_CHOICE = "multiple_choice"
    CHECKBOXES = "checkboxes"
    DROPDOWN = "dropdown"
    LINEAR_SCALE = "linear_scale"

class Question(BaseModel):
    """Represents a single parsed question from the Google Form.
    
    Attributes:
        id (str): A unique identifier (e.g., 'q_1').
        title (str): The main text/heading of the question.
        description (Optional[str]): Any subtitle or description text.
        type (QuestionType): The detected type of the question.
        required (bool): Whether the question is mandatory.
        options (List[str]): List of available options (empty for text inputs).
    """
    id: str
    title: str
    description: Optional[str] = None
    type: QuestionType
    required: bool = False
    options: List[str] = Field(default_factory=list)

class Persona(BaseModel):
    """Represents a generated human persona to simulate realistic responses.
    
    Attributes:
        name (str): Full name generated by Faker.
        email (str): Email address corresponding to the name.
        age (int): Age of the respondent.
        gender (str): Gender of the respondent.
        occupation (str): Job title or occupation.
        usage_frequency (str): How frequently they use the service/product.
        attitude_trait (str): General disposition (e.g., 'Netral', 'Kritis').
        latent_score (float): The anchor score (1.5 - 4.5) used as the mean for generating 
                              statistically valid normal distribution answers for Likert scales.
    """
    name: str
    email: str
    age: int
    gender: str
    occupation: str
    usage_frequency: str
    attitude_trait: str
    latent_score: float

class RespondentData(BaseModel):
    """Container for the complete generated response for a single persona.
    
    Attributes:
        respondent_id (int): Incremental ID representing the execution iteration.
        persona (Persona): The persona generated for this response.
        answers (Dict[str, Union[str, List[str]]]): Mapping of Question ID to the generated answer(s).
    """
    respondent_id: int
    persona: Persona
    answers: Dict[str, Union[str, List[str]]]  # key: question.id, value: answer(s)
    status: str = "Pending"
    db_id: Optional[int] = None